### ISSUE TITLE
[Feature Request] Make compatible with BetterChannelList

### ISSUE THREAD

**Issue by rauenzi** [TheLazySquid/DiscordWiderUserArea#1]
If I use this plugin to expand the channel width the user area does not keep up:

![image](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/6865942/74fc61e4-9440-4883-a861-3ad8d8f8eb6e)

Same happens when I shrink the list past normal

**Comment by TheLazySquid** [comment]
This should (in theory) be working now. Resizing the channels is a little laggy but I don't think that's this plugin's fault.
