### ISSUE TITLE
User Area not aligned

### ISSUE THREAD

**Issue by Shimaryu4k** [TheLazySquid/DiscordWiderUserArea#11]
Hiiii Im baack! I would like to report this mis aligned component. Discord latest update might be cause this bug.
Thank you!
![image](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/172479996/f52de6d3-35ee-4c6d-b406-afe998f52044)

**Comment by TheLazySquid** [comment]
Yep, it looks like the new update switched around some class names which caused it to break. This should now be fixed.
