### ISSUE TITLE
[Feature Request] Make compatible with Hide Channels

### ISSUE THREAD

**Issue by Razwerkz** [TheLazySquid/DiscordWiderUserArea#2]
When the WiderUserArea plugin is used alongside the [Hide Channels](https://github.com/Farcrada/DiscordPlugins/tree/master/Hide-Channels) plugin, the user area overlays onto the text input area when the channels panel is collapsed.

Expanded channels:
![Channels Panel Expanded](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/9700289/f70f2e3b-f5b1-4d87-abd2-223c330f1d09)

Collapsed channels:
![Channels Panel Collapsed](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/9700289/ba53982b-fc4f-421a-9ca6-f59c70fab15d)

Perhaps the user area could be shrank down to only show the user avatar and status icon when collapsed.

**Comment by TheLazySquid** [comment]
This should now be implemented. I made it so it compresses the user area and hide the buttons.

![image](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/76746384/eb5f32ae-2d99-43b8-8f49-ce3b9364451a)

**Comment by Razwerkz** [comment]
It works now, but...
![image](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/9700289/785d8f38-0298-4ff3-a519-44dc7771d93d)
...there's this interesting overlay effect when collapsed, that I'm sure is not intentional.

**Comment by TheLazySquid** [comment]
Never mind, the problem was on my side. I was using GameActivityToggle, which tweaked the styles of the user area. All it took to fix this was a single line of css.
