### ISSUE TITLE
Buggy User Area

### ISSUE THREAD

**Issue by TheBlackEntity** [TheLazySquid/DiscordWiderUserArea#5]
Sometimes the user area just glitches.

This can happen anytime you switch servers/dms or close the settings page.

Here's a preview:
![grafik](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/36412486/daf042bb-e09a-44d5-a756-24909c818366)

```md
## Discord Info
stable 286349 (4b5188e) Host 0.0.49 x64 Linux 64-bit (6.8.7)

## BetterDiscord
stable 1.10.1

### Theme:
- DiscordRecolor

### OS Info:
- NixOS
- X11
- KDE Plasma
```

I do have 48 plugins, so this could just be some incompatibility...

Also, the user pop-up is slightly cut off:
![grafik](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/36412486/66dd9afb-538d-468c-88dc-d7b6fbc82212)

**Comment by TheLazySquid** [comment]
Right you are! After a discord update dropped I didn't check my new selectors very carefully and ended up grabbing the wrong layer element, which led to it thinking it wasn't scaled when it was. This should now be fixed.

**Comment by TheLazySquid** [comment]
I also just went and added in some css to prevent the popup from going offscreen.
