### ISSUE TITLE
Plugin enables itself even when disabled in BD

### ISSUE THREAD

**Issue by VirtueAvatar** [TheLazySquid/DiscordWiderUserArea#8]
WiderUserArea is enabling itself even when BetterDiscord has it disabled. I didn't know what was going on and posted about it on the BetterDiscord server, and was told:

> It's a problem with the plugin. They're failing to remove one of their event listeners. You can report it on their repo

**Comment by TheLazySquid** [comment]
I fixed this a few days ago, try using the plugin from this repo rather than from the official plugin list.
