### ISSUE TITLE
Status aren't working properly

### ISSUE THREAD

**Issue by Shimaryu4k** [TheLazySquid/DiscordWiderUserArea#9]
Hi thank you for this amazing pluggin! however I got some small issues regarding alignments. I will just put a image here so you can understand what im talking about. Thanks!
![Screenshot 2024-06-12 153837](https://github.com/TheLazySquid/DiscordWiderUserArea/assets/172479996/4f713525-310a-4de6-a456-25529404ae68)

**Comment by TheLazySquid** [comment]
Really weird problem, but it should be fixed now. Update the plugin from [here](https://github.com/TheLazySquid/DiscordWiderUserArea/blob/main/build/WiderUserArea.plugin.js) since it'll be a bit until it's accepted onto the official repo.

**Comment by Shimaryu4k** [comment]
Its working properly now! Thanks! this is my first time using this github thing Im suprised how fast it got fixed! 
Thanks!! more power to you hehe
